"""Write ``docs/exercises.md`` from the exercise catalogue.

The catalogue is the source of truth; this renders it so the exercise list,
technique cues, muscle roles and sources can be read without the app.

    python -m tools.export_exercise_docs            # writes docs/exercises.md
    python -m tools.export_exercise_docs --check    # exit 1 if the file is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, "src")

from faceforge.exercise.catalog import exercises_in_category, get_exercise_catalog
from faceforge.exercise.model import Category, Role
from faceforge.exercise.motion_description import describe_transition, summarise_motions
from faceforge.exercise.muscle_groups import group_label
from faceforge.exercise.pose_library import neutral

OUT = Path("docs/exercises.md")


def _pose(p: dict) -> dict:
    full = neutral()
    full.update(p)
    return full


def render_exercise(defn) -> str:
    lines = [f"### {defn.name}", ""]
    lines.append(f"`{defn.id}` · {defn.category.value} · orientation: {defn.orientation} · "
                 f"anchor: {defn.anchor} · rep: {defn.rep_duration:.1f} s · "
                 f"equipment: {', '.join(e.kind.replace('_', ' ') for e in defn.equipment) or 'none'}")
    lines += ["", defn.description, ""]
    if defn.setup:
        lines.append("**Setup**")
        lines += [f"- {c}" for c in defn.setup]
        lines.append("")
    lines.append("**Phases** (pose reached at the end of each; joint motion from the previous)")
    lines.append("")
    lines.append("| phase | kind | s | moving joints | cues |")
    lines.append("|---|---|---|---|---|")
    prev = _pose(defn.phases[-1].pose)
    for ph in defn.phases:
        cur = _pose(ph.pose)
        motions = summarise_motions(describe_transition(prev, cur), max_lines=4)
        extra = []
        if ph.pitch:
            extra.append(f"trunk pitch {ph.pitch:+.0f}°")
        if ph.lift:
            extra.append(f"lift {ph.lift:.0f}")
        moving = "; ".join(motions + extra) or "hold"
        cues = " ".join(ph.cues)
        lines.append(f"| {ph.name} | {ph.kind.value} | {ph.duration:.2f} | {moving} | {cues} |")
        prev = cur
    lines.append("")
    lines.append("**Muscles**")
    for role, title in ((Role.PRIMARY, "Primary movers"), (Role.SECONDARY, "Synergists"),
                        (Role.STABILISER, "Stabilisers")):
        uses = defn.muscles_by_role(role)
        if not uses:
            continue
        parts = []
        for u in uses:
            side = f" ({u.side})" if u.side else ""
            note = f" — {u.note}" if u.note else ""
            parts.append(f"{group_label(u.group)}{side} {int(u.level * 100)} %{note}")
        lines.append(f"- *{title}:* " + "; ".join(parts))
    lines.append("")
    if defn.errors:
        lines.append("**Common errors**")
        lines += [f"- {c}" for c in defn.errors]
        lines.append("")
    if defn.physio_notes:
        lines.append("**Physiotherapy notes**")
        lines += [f"- {c}" for c in defn.physio_notes]
        lines.append("")
    lines.append("**Sources**")
    lines += [f"- {s}" for s in defn.sources]
    lines.append("")
    return "\n".join(lines)


def render(catalog) -> str:
    out = ["# Exercise catalogue", "",
           "Generated by `python -m tools.export_exercise_docs` from "
           "`faceforge.exercise.catalog`; do not edit by hand.", "",
           f"{len(catalog)} exercises. Peak levels are the activation the heatmap shows at the "
           "hardest point of the movement, as a fraction of maximal voluntary contraction; the "
           "phase model that scales them is described in `docs/exercise_animation.md`.", ""]
    out.append("## Contents")
    out.append("")
    for cat in Category:
        items = exercises_in_category(catalog, cat)
        out.append(f"- **{cat.value}** ({len(items)}): " +
                   ", ".join(f"[{d.name}](#{d.name.lower().replace(' ', '-').replace('(', '').replace(')', '').replace(',', '').replace('/', '').replace(':', '')})" for d in items))
    out.append("")
    for cat in Category:
        out.append(f"## {cat.value}")
        out.append("")
        for defn in exercises_in_category(catalog, cat):
            out.append(render_exercise(defn))
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args(argv)
    text = render(get_exercise_catalog())
    path = Path(args.out)
    if args.check:
        if not path.exists() or path.read_text() != text:
            print(f"{path} is stale; run python -m tools.export_exercise_docs")
            return 1
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"wrote {path} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
